# GitHub actions are pinned to commit hashes to ensure stability and security.

name: Deployability
on:
    pull_request:
        branches:
            - 'main'
jobs:
  Test-Sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        submodules: recursive
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: 3.12
    - run: python3 -m venv .venv
    - run: .venv/bin/python -m pip install wheel sphinx setuptools
    - run: .venv/bin/python -m pip install -e .[docs]
    - run: .venv/bin/python setup.py apidoc
    - run: .venv/bin/python setup.py build_sphinx -W
  Test-Sanity-Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        submodules: recursive
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: 3.12
    - run: python -m venv .venv
    - run: .venv\Scripts\pip install wheel setuptools
    - run: .venv\Scripts\pip install -e .[tests]
    - run: .venv\Scripts\python -m pytest

  Test-Sanity-OSX:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        submodules: recursive
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: 3.12
    - run: python3 -m venv .venv
    - run: .venv/bin/python -m pip install wheel
    - run: .venv/bin/python -m pip install -e .[tests]
    - run: .venv/bin/python -m pytest